config/routes.rb
Rails.application.routes.draw do
  
  # ホーム画面をrootに設定
  root 'top#index'

  # 本を探すためのルーティング 
  get    '/search', to: 'searchbooks#search'
  delete '/search', to: 'searchbooks#reset'
 
  # セッション機能のルーティング 
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # 「いいね」ランキング機能のページ遷移
  get '/ranking', to: 'books#ranking'

  # 所持する本を５段階評価する
  get '/evaluations', to: 'books#evaluations'
  
  # ユーザーのルーティングに所持する本の情報とフォロー機能をネスト 
  resources :users do
    resources :books, only: [:index, :show]
    member do
      get :following, :followers
    end
  end
 
  # 投稿とそれに対するコメントのルーティング 
  resources :posts do
    resources :comments, only: [:create]
  end

  # 本に対するレビューのルーティング
  resources :books do
    resource :reviews  
  end

  # フォローに関するルーティング
  resources :relationships, only: [:create, :destroy]

  # いいね機能のルーティング
  post 'like/:id'   => 'likes#create',  as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  
  has_many :comments, dependent: :destroy
  
  
  has_many :posts, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  
  
  attr_accessor :remember_token
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  
  has_secure_password
  
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def own?(object)
    self.id == object.user_id
  end
  
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signin_user, only: [:index, :show, :edit, :update, :destroy]
  
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザーの作成に成功しました'
      log_in(@user)
      remember @user
      redirect_to posts_path
    else
      flash[:danger] = 'ユーザーの登録に失敗しました'
      render 'new'
    end
  end  

  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params) && current_user
      flash[:success] = 'ユーザー情報を更新しました'
      redirect_to user_path(@user)
    else
      flash[:danger] = 'ユーザー情報の更新に失敗しました'
      render 'edit'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end
  
  def destroy
    user = User.find_by(id: params[:id])
    if current_user
      user.destroy
      flash[:success] = "ユーザーの削除に成功しました"
    end
  end
  
  def following
    @title = "Followings"
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  
    def signin_user
      redirect_to root_url unless log_in?
    end
    

  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="followings" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/edit.html.erb
<% provide :title, 'Edit information' %>

<%= render 'errors' %>
<div class="container">
  <%= form_for(@user) do |f|  %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    
    <%= f.submit '更新', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/index.html.erb
<% provide :title, 'Users' %>

<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <%= gravatar_for user %>
        <div class="card-body">
          <h3 class="card-title"><%= link_to user.name, user %></h3>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <% if current_user == user %>
                <%= link_to "編集", edit_user_path(user), class: "btn btn-sm btn-outline-secondary" %>
                <%= link_to "削除", user_path(user),method: :delete, class: "btn btn-sm btn-outline-secondary" %>
              <% end %>
            </div>
            <div class="stats">
              <a href="<%= following_user_path(user) %>">
                <strong id="followings" class="stat">
                  <%= user.followings.count %>
                </strong>
                following
              </a>
              <a href="<%= followers_user_path(user) %>">
                <strong id="followers" class="stat">
                  <%= user.followers.count %>
                </strong>
                followers
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide :title, 'Sing-in' %>

<%= render 'errors' %>
<div class="container">
  <%= form_for(@user) do |f|  %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    
    <%= f.submit '登録', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><b>Books:</b> <%= link_to @user.books.count, user_books_path(@user) %></span>
    </section>
    <section class="stats">
      <%= render 'stats' %>
    </section>
    <br/>
    <% if @user != current_user %>
      <%= render 'relationships/follow_button' %>
    <% end %>
  </aside>
  <% @posts = @user.posts.all.order(created_at: :desc) %>
    <div class="col-md-8">
      <% @posts.each do |post| %>
          <div>
              <%= gravatar_for post.user %>
              <%= post.user.name %>
              <%= link_to post.content, post_path(post), class: 'post-content' %>
              <hr/>
          </div>
      <% end %>
    </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>


<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Books:</b> <%= link_to @user.books.count, user_books_path(@user) %></span>
    </section>
    <section class="stats">
      <%= render 'stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= gravatar_for(user) %>
            <%= link_to user.name, user %>
            <hr/>
          <% end %>
        </div>
      <% end %>
  </div>
</div>