config/routes.rb
Rails.application.routes.draw do
  
  # ホーム画面をrootに設定
  root 'top#index'

  # 本を探すためのルーティング 
  get    '/search', to: 'searchbooks#search'
  delete '/search', to: 'searchbooks#reset'
 
  # セッション機能のルーティング 
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # 「いいね」ランキング機能のページ遷移
  get '/ranking', to: 'books#ranking'

  # 所持する本を５段階評価する
  get '/evaluations', to: 'books#evaluations'
  
  # ユーザーのルーティングに所持する本の情報とフォロー機能をネスト 
  resources :users do
    resources :books, only: [:index, :show]
    member do
      get :following, :followers
    end
  end
 
  # 投稿とそれに対するコメントのルーティング 
  resources :posts do
    resources :comments, only: [:create]
  end

  # 本に対するレビューのルーティング
  resources :books do
    resource :reviews  
  end

  # フォローに関するルーティング
  resources :relationships, only: [:create, :destroy]

  # いいね機能のルーティング
  post 'like/:id'   => 'likes#create',  as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one :review
  has_many :posts, dependent: :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    user = User.find_by(id: params[:user_id])
    @books = user.books.all.page(params[:page]).per(6)
  end
  
  def show
    @book =Book.find_by(id: params[:id])
    book_reviews @book
    books = Book.where(isbn: @book.isbn)
    @posts = Post.where(book_id: books.ids).order(created_at: :desc).page(params[:page]).per(10)
  end

  
  def new
  end
  
  def create
    @book = current_user.books.find_or_initialize_by(isbn: params[:isbn])
    unless @book.persisted?
      results = RakutenWebService::Books::Book.search(isbn: @book.isbn)
      @book = current_user.books.build(read(results.first))
      @book.save
      flash[:success] = '保存しました'
      redirect_to posts_url
    end
  end
    
    
  def destroy
    @book = Book.find_by(id: params[:id])
    @book.destroy
    flash[:success] = '削除しました'
    redirect_to posts_url
  end
  
  def ranking
    @books = Book.all.group_by(&:isbn)
    # 月間いいねの数をカウント
    rank @books
  end
  
  
  private
  #「楽天APIのデータから必要なデータを絞り込む」、且つ「対応するカラムにデータを格納する」メソッドを設定していきます。
  def read(result)
    title = result["title"]
    author = result["author"]
    url = result["itemUrl"]
    isbn = result["isbn"]
    image_url = result["mediumImageUrl"].gsub('?_ex=120x120', '')
    {
      title: title,
      author: author,
      url: url,
      isbn: isbn,
      image_url: image_url
    }
  end
  
  
end
 

app/helpers/books_helper.rb
module BooksHelper
    
  def book_reviews(book)
    books = Book.where(isbn: book.isbn)
    total = 0
    count = 0
    books.each do |book|
      unless book.review.nil?
       total += book.review.evaluation
       count += 1 
      end 
    end
    if count != 0
      @eval_avg = total / count
    else
      @eval_avg = 0
    end
  end

  def rank(books)
    book_like_count = {}
    monthly_likes = Like.all.where(created_at: Time.current.all_month) 
    books.values.each do |book|
      likes = 0
      book.each do |b|
        likes += monthly_likes.where(post_id: b.posts.ids).pluck(:id).count
      end
      book_like_count.store(book[0], likes)
    end
    @book_liked_ranks = book_like_count.sort_by{ |_,v| v }.reverse.to_h.take(5) 
  end
end

app/views/books/_book_list.html.erb
<% if @books %>
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-md-3">
        <div class="card mb-3 shadow-sm">
          <%= image_tag book.medium_image_url %>
          <div class="card-body">
            <p class="card-text"><%= book.title %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= form_tag books_path do %>
                   <%= hidden_field_tag :isbn, book.isbn %>
                   <%= submit_tag 'save', class:"btn btn-sm btn-outline-secondary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/index.html.erb
<% provide(:title, 'Books') %>
<% @user = User.find_by(id: params[:user_id]) %>
<% if current_user == @user %>
  <%= link_to '本を追加する', '/search', class:"btn btn-primary my-2" %>
  <hr/>
<% end %>
<div class="row scroll">
  <% @books.each do |book| %>
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <%= link_to book_path(book) do %>
          <%= image_tag book.image_url, width: '100%' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<%= paginate @books %>

app/views/books/ranking.html.erb
<h3>月間ランキング</h3>
<br/>
<div class="scroll">
  <% @book_liked_ranks.each.with_index(1) do |(book,like),index| %>
    <div class="rank">
      <h3>第<%= index %>位</h3>
      <%= link_to book_path(book) do %>
        <%= image_tag book.image_url,width:'100px',class:'rank-image' %>
      <% end %>
      <div class="rank-info">
        <h4>タイトル：<%= book.title %></h4>
        <p>著者：<%= book.author %>　累計：<strong><%= like %></strong>いいね</p>
      </div>
    </div>
    <hr/>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="row">
    <aside class="col-md-4">
      <%= image_tag @book.image_url,width: '320px'%>
      <hr/>
      <% unless current_user.books.include?(@book)  %>
        <%= form_tag books_path do %>
           <%= hidden_field_tag :isbn, @book.isbn %>
           <%= submit_tag '図書に追加する', class:"btn btn-sm btn-outline-secondary" %>
        <% end %>
      <% end %>
    </aside>
    <div class="col-md-8">
      <h3><%= @book.title %> | <%= @book.author %></h3>
      <h4>
        <span>全体評価：</span>
        <span id="star-rate-<%= @book.id %>"></span>
        <script>
          $('#star-rate-<%= @book.id %>').raty({
            size: 36,
            starOff: "<%= asset_path('star-off.png') %>",
            starOn: "<%= asset_path('star-on.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            half: true,   
            readOnly: true,
            score: <%= @eval_avg %>, 
          });
        </script> 
        <%= @eval_avg %>
      </h4>
      <% if @book.review && current_user.id == @book.user_id %>
        <%= link_to("評価を編集", edit_book_reviews_path(@book), class:"btn btn-secondary btn-sm") %>
      <% else %>
        <%= link_to("評価をする", new_book_reviews_path(@book), class: "btn btn-primary btn-sm") %>
      <% end %>
      <hr/>
      <h4>関連ツイート</h4>
      <div class="minimum-scroll" >
        <% @posts.each do |post| %>
          <div>
            <%= gravatar_for post.user %>
            <%= post.user.name %>
            <%= link_to post.content, post_path(post), class: 'post-content' %>
            <hr/>
          </div>
        <% end %>
      </div>
      <br/>
      <%= paginate @posts %>
    </div>
</div>