config/routes.rb
Rails.application.routes.draw do
  
  # ホーム画面をrootに設定
  root 'top#index'

  # 本を探すためのルーティング 
  get    '/search', to: 'searchbooks#search'
  delete '/search', to: 'searchbooks#reset'
 
  # セッション機能のルーティング 
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # 「いいね」ランキング機能のページ遷移
  get '/ranking', to: 'books#ranking'

  # 所持する本を５段階評価する
  get '/evaluations', to: 'books#evaluations'
  
  # ユーザーのルーティングに所持する本の情報とフォロー機能をネスト 
  resources :users do
    resources :books, only: [:index, :show]
    member do
      get :following, :followers
    end
  end
 
  # 投稿とそれに対するコメントのルーティング 
  resources :posts do
    resources :comments, only: [:create]
  end

  # 本に対するレビューのルーティング
  resources :books do
    resource :reviews  
  end

  # フォローに関するルーティング
  resources :relationships, only: [:create, :destroy]

  # いいね機能のルーティング
  post 'like/:id'   => 'likes#create',  as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  has_many :comments, dependent: :destroy
  
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  validates :book_id, presence: true
  validates :content, presence: true, length: { maximum: 100 }
  validates :user_id, presence: true
  validates :book_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
    @post = current_user.posts.build
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿しました'  
      redirect_to posts_url
    else
      flash[:danger] = '投稿に失敗しました'
      redirect_to posts_url 
    end
  end
  

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      flash[:success] = '編集に成功しました'
      redirect_to posts_url
    else
      flash[:danger] = '編集に失敗しました'
      render 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = '投稿を削除しました'
      redirect_to posts_url
    else
      flash[:danger] = '削除に失敗しました'
      render 'show'
    end
  end
  
  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.comments.order(created_at: :desc)
  end

  def index
    followings_member = current_user.followings
    @posts = Post.where(user_id: [current_user.id, *followings_member.ids]).order(created_at: :desc).page(params[:page]).per(10)
  end
  
  private
  def post_params
    params.require(:post).permit(:content,:user_id,:book_id)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<div class="small-scroll">
  <% @comments.each do |c| %>
    <div>
      <%= gravatar_for c.user %>
      <a href="/users/<%= @post.user.id %>"><%= c.user.name %></a>
      <%= c.comment_content %>
      <hr>
    </div>
  <% end %>
</div>

app/views/posts/_errors.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_post.html.erb
  <span id="post_<%= @post.id %>">
    <%= @post.likes.count %>
    <% if current_user.already_liked?(@post) %>
      <%= link_to destroy_like_path(@post), class: "like-link", method: :DELETE, remote: true do %>
        <i class="fa fa-heart unlike-btn"></i>
      <% end %>
    <% else %>
      <%= link_to create_like_path(@post), class: "like-link", method: :POST, remote: true do %>
        <i class="far fa-heart like-btn"></i>
      <% end %>
    <% end %>
  </span>

app/views/posts/_post_form.html.erb
<% @post = current_user.posts.new %>
<%= render 'errors' %>
<% @books = current_user.books %>
<%= form_for(@post) do |f|  %>
  <%= f.collection_select :book_id, @books.all, :id, :title, {prompt: "本を選択してください"}, {class: "form-control"} %>
  <%= f.text_area :content, class: 'form-control' %>
  
  <%= f.submit '投稿', class: 'btn btn-primary post-btn' %>
<% end %>

app/views/posts/_user_profile.html.erb
<section class="user_info">
  <h1>
    <%= gravatar_for current_user %>
    <%= current_user.name %>
  </h1>
  <span><%= link_to "HOME", current_user %> |</span>
  <span><b>Books:</b> <%= link_to current_user.books.count,  user_books_path(current_user) %></span>
</section>
<div class="stats">
  <a href="<%= following_user_path(current_user) %>">
    <strong id="followings" class="stat">
      <%= current_user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(current_user) %>">
    <strong id="followers" class="stat">
      <%= current_user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/posts/edit.html.erb
<% provide :title, 'Edit post' %>

<div class="container">
  <%= form_for(@post) do |f|  %>
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
    
    <%= f.submit '登録', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="row">
    <aside class="col-md-4">
      <%= render 'user_profile' %>
      <hr/>
      <%= render 'post_form' %>
    </aside>
    <div class="col-md-8">
      <h2>Posts</h2>
      <div class="scroll" >
        <% @posts.each do |post| %>
          <div>
            <%= gravatar_for post.user %>
            <%= post.user.name %>
            <%= link_to post.content, post_path(post), class: 'post-content' %>
            <hr/>
            </div>
        <% end %>
      </div>
      <br/>
      <%= paginate @posts %>
    </div>
</div>

app/views/posts/show.html.erb
<%= provide :title, 'Post Detail' %>
<div class="post-text" >
  <div class="row">
    <div class="col-md-2">
      <div>
        <div class="card mb-3 shadow-sm">
          <%= link_to book_path(@post.book) do %>
            <%= image_tag @post.book.image_url, width: '100%' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <%= gravatar_for @post.user %>
      <%= link_to @post.user.name,user_path(@post.user) %>
      <hr/>
      <div class="post-content">
        <p><%= @post.content %></p>
      </div>
      <hr/>
      <%= render 'post', post: @post %>
      <small class="created_at"><%= @post.created_at %></small>
      <% if current_user == @post.user %>
        <%= link_to post_path(@post) ,method: :delete do %>
          <i class="far fa-trash-alt post-trash"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <br/>
</div>
  <%= render 'comments/form_comment', post: @post %>
  <br/>
  <% if @post.comments.any? %>
    <%= render 'comments' %>
  <% end %>